// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230622133037_Database")]
    partial class Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(100)")
                        .HasColumnName("id_komen");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("tgl_komentar");

                    b.Property<string>("ContentComment")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("isi_komentar");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("API.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_bahan");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nm_bahan");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jumlah");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("satuan");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("API.Models.Recipe", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("id_recipe");

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wkt_memasak");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("deskripsi");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("kesulitan");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bahan");

                    b.Property<string>("PrepareTime")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wkt_persiapan");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nm_resep");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("langkah");

                    b.HasKey("RecipeId");

                    b.ToTable("tb_m_recipe");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("char(5")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("tb_user");
                });
#pragma warning restore 612, 618
        }
    }
}
